### PR TITLE
Add options and support for changing initial data behavior

### PR DESCRIPTION
**Pull request by droidenator**
This addresses the question raised in #1.

I've added an `options` object that is passed in when creating a new instance of `SSE`. Currently it accepts one option: `isQueue`. If `isQueue` is true, the initial data will be sent out as individual messages. That is, an initial data array with 5 items would send 5 five messages. 

If `isQueue` is false, the initial message will be send as a single message. An array of 5 items would send one message consisting of a array with the five messages.

I've defaulted `isQueue` to `true` to maintain the current functionality. 

I also replace `forEach` with `reduce` and now use `send` instead of `res.write` for sending messages. This was to consolidate the functionality for sending messages in one function that is used in both places.

### CODE REVIEW

**Comment by dpskvn** [comment]
I'm going to review this over the weekend. While this is pretty much what I had in mind, I'm still not 100% sold on implementing this option at all. The idea behind `express-sse` was to keep everything as simple as possible. 

Opening up a configuration object is something I want to think carefully about, especially since its only use here is to achieve something that can also be done by passing a nested array to the constructor.

**Comment by droidenator** [comment]
This one is tricky. Where things could get confusing to a user, I'd think, is that if they were to call `sse.send(['a','b','c'])`, it'd send one message containing the array. If they set that as their initial message, they'd get three. I think giving users the options to choose between a queue and a single message would make the behavior a little more..predictable? But that being said, if you had `isQueue` true and passed sent the same array of data via `init` and `send`, they'd each send differently. 

I understand wanting to keep things as simple as possible. I think the options adds a little more flexibility for people who might need it or want it without any additional complexity. For most use cases they probably won't care about `isQueue` and it'll work just fine.

**Comment by droidenator** [comment]
To elaborate on what I had said earlier: I think the biggest confusion could be the way an array is handled if the sending of it is triggered via `sse.init` vs `sse.send`. 

I could see it be confusing to a user because they'd have to wrap their array in an array if they wanted to use it as the initial data payload but, for send, they could just use a single array. Really the only way to get what I would expect to be "normal" behavior would be if `isQueue` is false. Then, regardless if the array was sent with `sse.init` or `sse.send`, the argument would be the same (no wrapping the array in an array) and would be delivered to the client the same. That, however, would break stuff for any users who expect to be able to just feed in an array as their initial data and get a series of messages. 

Sorry. Not trying to write a novel here. Just trying to sort out my thoughts a bit. :)

**Comment by dpskvn** [comment]
Okay, let's do this, but I'm going to close this pull request and you can make a new one against the `serialize` branch.

Let's call the setting `isSerialized` and allow another option to give the non-serialized (non-queued) initial sends a custom event name (in case users want to do so).

I've introduced a new method called `serialize` and that one can be used to send events if `isSerialized` is `true`.

To further explain why I didn't merge this first, I was already working on the `serialize` branch when this pull request was made and I didn't want the commit history showing me overwriting most of your contributions. 

If you feel like expanding the test spec for these new options, that'd be great.

**Pull request closed without merging**
